/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface TlkButton {
        "theme": any;
    }
    interface TlkPortal {
        "appendTo": (newContainer: HTMLElement) => Promise<void>;
        "container": HTMLElement;
        "onAnimationEnd": (event: AnimationEvent) => void;
        "onAnimationStart": (event: AnimationEvent) => void;
        "onMounted": (portalElement: HTMLElement) => void;
        "onTransitionEnd": (event: TransitionEvent) => void;
        "theme": any;
    }
    interface TlkThemeManager {
        "avoidInheritStyles": boolean;
        "onMounted": (themeManagerElement: HTMLElement) => void;
        "styles": object;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLTlkButtonElement extends Components.TlkButton, HTMLStencilElement {
    }
    var HTMLTlkButtonElement: {
        prototype: HTMLTlkButtonElement;
        new (): HTMLTlkButtonElement;
    };
    interface HTMLTlkPortalElement extends Components.TlkPortal, HTMLStencilElement {
    }
    var HTMLTlkPortalElement: {
        prototype: HTMLTlkPortalElement;
        new (): HTMLTlkPortalElement;
    };
    interface HTMLTlkThemeManagerElement extends Components.TlkThemeManager, HTMLStencilElement {
    }
    var HTMLTlkThemeManagerElement: {
        prototype: HTMLTlkThemeManagerElement;
        new (): HTMLTlkThemeManagerElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "tlk-button": HTMLTlkButtonElement;
        "tlk-portal": HTMLTlkPortalElement;
        "tlk-theme-manager": HTMLTlkThemeManagerElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface TlkButton {
        "onMounted"?: (event: CustomEvent<any>) => void;
        "theme"?: any;
    }
    interface TlkPortal {
        "container"?: HTMLElement;
        "onAnimationEnd"?: (event: AnimationEvent) => void;
        "onAnimationStart"?: (event: AnimationEvent) => void;
        "onMounted"?: (portalElement: HTMLElement) => void;
        "onTransitionEnd"?: (event: TransitionEvent) => void;
        "theme"?: any;
    }
    interface TlkThemeManager {
        "avoidInheritStyles"?: boolean;
        "onMounted"?: (themeManagerElement: HTMLElement) => void;
        "styles"?: object;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "tlk-button": TlkButton;
        "tlk-portal": TlkPortal;
        "tlk-theme-manager": TlkThemeManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "tlk-button": LocalJSX.TlkButton & JSXBase.HTMLAttributes<HTMLTlkButtonElement>;
            "tlk-portal": LocalJSX.TlkPortal & JSXBase.HTMLAttributes<HTMLTlkPortalElement>;
            "tlk-theme-manager": LocalJSX.TlkThemeManager & JSXBase.HTMLAttributes<HTMLTlkThemeManagerElement>;
        }
    }
}
